<a href="https://colab.research.google.com/github/deeksha3111/23/blob/main/Copy_of_Copy_of_C_140.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install kaggle

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (6.1.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2022.9.24)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.64.1)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)

In [ ]:
#Upload kaggle.json here, that we downloaded in C-138

from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"cintyyy","key":"4997b9bca2253c3879ca90ca9e9667e6"}'}

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d tmdb/tmdb-movie-metadata

Downloading tmdb-movie-metadata.zip to /content
  0% 0.00/8.89M [00:00<?, ?B/s]
100% 8.89M/8.89M [00:00<00:00, 176MB/s]

In [ ]:
!ls

kaggle.json  sample_data  tmdb-movie-metadata.zip

In [ ]:
!unzip tmdb-movie-metadata.zip

Archive:  tmdb-movie-metadata.zip
  inflating: tmdb_5000_credits.csv
  inflating: tmdb_5000_movies.csv

In [ ]:
!ls

kaggle.json  tmdb_5000_credits.csv  tmdb-movie-metadata.zip
sample_data  tmdb_5000_movies.csv

In [ ]:
import pandas as pd 
import numpy as np 

df1=pd.read_csv('tmdb_5000_credits.csv')
df2=pd.read_csv('tmdb_5000_movies.csv')

In [ ]:
df1.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
df2.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
df1.columns = ['id','tittle','cast','crew']
df2= df2.merge(df1,on='id')

df2.head(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,tittle,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

# Demographic Filtering

In [ ]:
C = df2['vote_average'].mean()
print(C)

6.092171559442016

In [ ]:
m = df2['vote_count'].quantile(0.9)
print(m)

1838.4000000000015

In [ ]:
q_movies = df2.copy().loc[df2['vote_count'] >= m]
print(q_movies.shape)

(481, 23)

In [ ]:
def weighted_rating(x, m=m, C=C):
    v = x['vote_count']
    R = x['vote_average']
    return (v/(v+m) * R) + (m/(m+v) * C)

q_movies['score'] = q_movies.apply(weighted_rating, axis=1)

In [ ]:
q_movies = q_movies.sort_values('score', ascending=False)
q_movies[['title', 'vote_count', 'vote_average', 'score']].head(10)

,title,vote_count,vote_average,score
1881,The Shawshank Redemption,8205,8.5,8.059258
662,Fight Club,9413,8.3,7.939256
65,The Dark Knight,12002,8.2,7.920020
3232,Pulp Fiction,8428,8.3,7.904645
96,Inception,13752,8.1,7.863239
3337,The Godfather,5893,8.4,7.851236
95,Interstellar,10867,8.1,7.809479
809,Forrest Gump,7927,8.2,7.803188
329,The Lord of the Rings: The Return of the King,8064,8.1,7.727243
1990,The Empire Strikes Back,5879,8.2,7.697884

In [ ]:
import plotly.express as px

fig = px.bar((q_movies.head(10).sort_values('score', ascending=True)), x="score", y="title", orientation='h')
fig.show()

# Content Based Filtering

In [ ]:
#The general idea behind content based filtering is that if a person likes a particular item, he or she will also like an item that is similar to it.

#features like cast, crew, keywords and genres. Here, we mean that if the cast, the crew, the keywords or the genre of Movie A and Movie B are similar (with least differences),
# and a user likes Movie A then we can recommend Movie B to the user!

#Let us first see how these columns look like in our DataFrame.
df2[['title', 'cast', 'crew', 'keywords', 'genres']].head(3)

,title,cast,crew,keywords,genres
0,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."
1,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""..."
2,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."

In [ ]:
#Here, it looks like all the data is in a list of dictionaries.However, there might be a few rows that may be in string format but are a list of dictionaries! To eliminate that
#factor and ensure all our rows are list of dictionaries, we can use a python’s module literal_eval() which would safely check for us what datatype our data is meant to be and 
#convert it into the same (only if it a string, otherwise no changes happen):

from ast import literal_eval
#Here, we have listed down all the features that we want to evaluate, iterated over these features and then applied the literal_eval() function to all the values of the
#feature column in our DataFrame df2.

features = ['cast', 'crew', 'keywords', 'genres']
for feature in features:
    df2[feature] = df2[feature].apply(literal_eval)

df2.dtypes

budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title                    object
vote_average            float64
vote_count                int64
tittle                   object
cast                     object
crew                     object
dtype: object

In [ ]:
#We currently have all the data as a list of dictionaries, however it would be extremely easy for us to have the data as a list!
#Data like Cast, Keywords and Genres should be as a list of elements instead of a list of dictionaries.

#Next, we also want to know the name of the director, which is available in the crew column! It would be great for us if we could have the names of the directors of these movies
# in a separate column in our dataframe.

#a function to find out the name of the director of the movie and store it in a separate DataFrame.
def get_director(x):
    for i in x:
# We are checking if the key job in any of the dictionaries matches with the word Director and if it does, we are returning the name of the director.     
        if i['job'] == 'Director':
            return i['name']
#Here, make sure that if you cannot find the name of the director, then store NaN value in the DataFrame. NaN in Pandas Dataframe is used to represent None values.
    return np.nan
#Finally, we are applying this function on the crew column of our Dataframe, and saving the value it returns to a new column director
df2['director'] = df2['crew'].apply(get_director)

In [ ]:
#we want to convert the list of dictionaries in the columns cast, keywords and genres into simple lists.
#Now for this, make sure that you cross check if the value of the column is a list or not. Python has a function isinstance() to do the same.

def get_list(x):
#Here, we have a function named get_list() in which we are first checking if the value x is an instance of list or not using the isinstance() method. 
    if isinstance(x, list):
        names = [i['name'] for i in x]
#If it is, we are finding all the names values in all dictionaries inside the list and storing them in a list.
        return names
#If it’s not, we are returning an empty list since it was not already a list of dictionaries.
    return []
#Lastly, we define the names of the columns on which we want to apply this function. We are then iterating over all the features/names of the columns and then using the apply()
#function to apply the function we created on all the columns!
features = ['cast', 'keywords', 'genres']
for feature in features:
    df2[feature] = df2[feature].apply(get_list)

In [ ]:
df2[['title', 'cast', 'director', 'keywords', 'genres']].head(3)
# There might be multiple actors with the same name. Is our computer smart enough to find the difference between Johnny with a Capital J and johnny with a small j?

,title,cast,director,keywords,genres
0,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",James Cameron,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]"
1,Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",Gore Verbinski,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]"
2,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",Sam Mendes,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]"

In [ ]:
#we are converting all the values in columns cast, keywords, director and genres to lowercase. Let’s also remove the spaces from the elements of these lists since we are going to
#create a metadata string for all the movies.
#Please note that while the columns cast, keywords and genres are a list of elements, director is a string. We need to handle these differently
def clean_data(x):
  #checking if the value x is an instance of list or not using the isinstance()If it is, we are converting all the values to lowercase using the lower() function and replacing the
  # “ ” with “”. Since lower() is a method that can be applied on Strings, we are using it with str, which is a default Python’s data type for strings.
    if isinstance(x, list):
        return [str.lower(i.replace(" ", "")) for i in x]
    else:
#If, however, our item was not a list, we are then checking if it is a string. Remember that we saved NaN values where we didn’t find the name of the director, hence, this is 
#necessary to check. If it is a string, we are again converting it to lowercase and replacing “ ” with “”. If it was not a string (and was NaN since that is the only value it can 
# be), we are returning an empty string.
        if isinstance(x, str):
            return str.lower(x.replace(" ", ""))
        else:
            return ''
#We are finally applying this function to the columns cast, keywords, director and genres.
features = ['cast', 'keywords', 'director', 'genres']
for feature in features:
    df2[feature] = df2[feature].apply(clean_data)

In [ ]:
#To convert a list of elements into a string, we have join() method. What the join method does is that it will take all the elements of the list,join them together and then return it in
#string format.
#create the string of metadata. We want to separate all the elements of keywords, cast and genres with space and we want to keep space between these column values as well.

def create_soup(x):
#Here, we are first joining the keywords, then the cast, then adding the name of the director to it and then joining the genres in create_soup() function. This will give us a 
#string of all the metadata about a movie.
    return ' '.join(x['keywords']) + ' ' + ' '.join(x['cast']) + ' ' + x['director'] + ' ' + ' '.join(x['genres'])
#we are applying the function create_soup on our dataframe. Here, since we are not applying the function to a particular column but to an entire row of dataframe, we are giving
# anadditional attribute axis=1 to our apply() function, which means that we want the returning value to be treated along a column soup, instead of considering it as the index.
df2['soup'] = df2.apply(create_soup, axis=1)

In [ ]:
#we want to remove the stop words. Stop words are the words that do not add any value to a given sentence but are only there to make it grammatically correct. Words like The, And, But,
#etc. are all stop words.Secondly, it is easier for computers to compare two arrays. We want to create an array that will count all the words in our metadata string and
#maintain a count for each of the words. This will help us find similarity between two movies!

from sklearn.feature_extraction.text import CountVectorizer
#Here, we are first importing the CountVectorizer. We are then counting all the words after removing the stop words and then we are converting it into a matrix, or a 3d
#array (list of lists).
count = CountVectorizer(stop_words='english')
count_matrix = count.fit_transform(df2['soup'])

In [ ]:
#We are then finally going to import the cosine_similarity function from sklearn and create a classifier based on our data with it.
from sklearn.metrics.pai
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim2 = cosine_similarity(count_matrix, count_matrix)

In [ ]:
#we want to change the index of our movie data to the name of the movies.
#Here, we are resetting our data for df2 
df2 = df2.reset_index() 
#and then we are changing the index to the title of the movie.
indices = pd.Series(df2.index, index=df2['title'])

In [ ]:
#Finally, we will create the function that will get recommendations for us using our cosine_similarity classifier that we created earlier.

#Here, we are passing the title of the movie that the user likes and our classifier.
def get_recommendations(title, cosine_sim):
  #We are then finding the index of the movie in our dataframe using the indices variable we created earlier, which contains the indexes of all the movies in the dataframe. 
  # We created this when we changed the index of our dataframe to the title of the movie.

  idx = indices[title] 
  #Next, we are creating a list of all the scores of the movies. This is the score of similarity of each movie with what the user likes
  sim_scores = list(enumerate(cosine_sim[idx]))
  #using the sorted function on our data to sort the scores of all the movies and we are reversing its order with reverse=True attribute.
  sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
  #We are then taking elements from 1:11. We are not starting with 0 since the movie that the user likes will have the highest score (perfect score)
  sim_scores = sim_scores[1:11]
  # We are then taking out the indexes of all the movies that we want to recommend and finally we are returning the titles of all the movies that our system recommends!
  movie_indices = [i[0] for i in sim_scores]
  return df2['title'].iloc[movie_indices]

In [ ]:
#calling the above function for different titles.
get_recommendations('Fight Club', cosine_sim2)

1553                       Se7en
946                     The Game
421                       Zodiac
4564    Straight Out of Brooklyn
45                   World War Z
4462          The Young Unknowns
3863                      August
3043            End of the Spear
1010                  Panic Room
4101                Full Frontal
Name: title, dtype: object

In [ ]:
get_recommendations('The Shawshank Redemption', cosine_sim2)

4638    Amidst the Devil's Wings
690               The Green Mile
4408              Jimmy and Judy
1247             City By The Sea
4502               Water & Power
4529           Hurricane Streets
559                 The Majestic
1752              Kiss the Girls
2818                     Witness
4564    Straight Out of Brooklyn
Name: title, dtype: object

In [ ]:
get_recommendations('The Godfather', cosine_sim2)

2731      The Godfather: Part II
867      The Godfather: Part III
4638    Amidst the Devil's Wings
4209            The Conversation
3293                 10th & Wolf
2255                   The Yards
1394               Donnie Brasco
3012               The Outsiders
4124          This Thing of Ours
1018             The Cotton Club
Name: title, dtype: object

In [ ]:
from google.colab import files
df2.to_csv('movies.csv')
files.download('movies.csv')